# One should also update asterinas/src/commands/new/rust-toolchain.toml.template
# when updating this
[toolchain]
# channel = "nightly-2024-06-20"
# channel = "nightly-2023-10-05"
components = ["rust-src", "rustc-dev", "llvm-tools-preview"]
channel = "nightly-2023-11-23"
